clear;
Dateiname = 'Fehler_ZUL_din.xlsx';
%% init variables
%res = 15;    % resolution of plot / number of sampling points
%relativeHumidity = linspace(10, 90, res);
%temperature = linspace(1, 30, res);
relativeHumidity = [44.79082664;43.53677908;48.29541481;37.45150963;55.08983242;45.4886683;39.91532807;53.038443;45.82429377;49.27260377;21.14864918;26.22538133;33.05387276;42.21668934;53.162605;57.10906307;48.29559929;55.36573946;41.16578228;45.78984548;61.02402038;61.53390488;66.52191303];
temperature = [20.39292318;18.93342753;21.77691894;20.39325646;20.4289708;21.12283917;21.14754156;20.8808746;20.18092279;24.38848095;12.67709015;12.67661395;12.68358365;12.74851865;12.82644672;16.12443638;16.10143634;16.23493629;16.1964365;18.98564221;18.96642759;18.84992745;21.54741882];

ambientPressure = 1013;

% error range - take care that range has to be the full span of error
% e.g. +/-2 results in an error of 4 !
errorRelativeHumidity = 7;
errorAmbientPressure = 50;
errorTemperature = 0.0425; % for PT 100 1/10 DIN class B at 25 °C

linErrorAbs = zeros(2,23);
% errorOverErrorRelativeHumidity = zeros(3,3,3);
linErrorAbs = ones(23,1);

for i = 1 : 23
   
%         if temperature(i) < 0
%             errorTemperature = 7*(-temperature(i)/10)+0.3;
%         elseif temperature(i) >= 0
%             errorTemperature = 10*(temperature(i)/20)+0.3;
%         end
%     
        tempError = humidAir_errorPropagationRHtoX(...
        relativeHumidity(i), errorRelativeHumidity, ...
        temperature(i), errorTemperature, ...
        ambientPressure, errorAmbientPressure);
        
        linErrorAbs(i,1) = tempError;
    
end


basis(:,1) = relativeHumidity(:);
basis(:,2) = temperature(:);

[X,Y]= ndgrid(basis(1,:), basis(2,:));

Z = linErrorAbs(:,:);

%Tabel erzeugen
ExTab = table(Z,basis);
%in Excelfile schreiben
writetable(ExTab,Dateiname,'WriteRowNames',true);

    
%        %  Auto-generated by MATLAB on 27-Nov-2015 08:52:23
% 
%         % Create figure
%         figure1 = figure('PaperSize',[20.98404194812 29.67743169791],...
%             'InvertHardcopy','off',...
%             'Color',[1 1 1]);
%         colormap('hsv');
% 
%         % Create axes
%         axes1 = axes('Parent',figure1,'ZMinorTick','on','ZMinorGrid','on',...
%             'Position',[0.15597667638484 0.0974658869395711 0.628279883381924 0.769980506822612],...
%             'FontSize',12);
%         %% Uncomment the following line to preserve the X-limits of the axes
%         % xlim(axes1,[0 100]);
%         %% Uncomment the following line to preserve the Y-limits of the axes
%         % ylim(axes1,[0 30]);
%         %% Uncomment the following line to preserve the Z-limits of the axes
%         % zlim(axes1,[0 1.4]);
%         view(axes1,[0.0 90]);
%         grid(axes1,'on');
%         hold(axes1,'all');
% 
%         % Create surf
%         surf(X,Y,Z,'Parent',axes1,'FaceColor','flat');
% 
%         % Create xlabel
%         xlabel({'relative humidity in %'},'FontWeight','demi','FontSize',13);
% 
%         % Create ylabel
%         ylabel({'temperature in °C'},'FontWeight','demi','FontSize',13);
% 
%         % Create zlabel
%         zlabel({'dx in g/kg'},'FontWeight','demi','FontSize',13);
% 
%         % Create title
%         varTitle1 = strcat('measurement uncertainty of water load');
%         varTitle2 = strcat('+/-', num2str(errorRelativeHumidity/2) ,' % RH, +/-',num2str(errorTemperature/2) ,' K, +/-',num2str(errorAmbientPressure/2) ,' hPa','  (p =', num2str(ambientPressure) ,'hPa)');
%         title({varTitle1, varTitle2},...,
%             'FontSize',14);
% 
%         % Create colorbar
%         colorbar('peer',axes1,[0.891394557823129 0.11 0.0388726919339164 0.815],...
%             'FontSize',12);